[package]
name = "amd_smi_lib_rs"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["WhiskyAKM"]
description = "bindings for amd_smi"

[dependencies]
amd_smi_lib_sys = "0.1.0"
bitflags = "2.9.1"
